service: life-backend
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

functions:

plugins:
  - serverless-esbuild
  - serverless-offline

custom:
  esbuild:
    watch:
      pattern: ["src/**/*.ts"] # match only typescript files in src directory
      ignore: ["temp/**/*"]
