service: airstats-backend

frameworkVersion: "3"

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'local'}
  region: eu-west-1
  environment:
    DATABASE_URL: ${env:DATABASE_URL}

plugins:
  - serverless-esbuild
  - serverless-offline

package:
  individually: true

functions:
  hello:
    handler: src/api/getFlight/index.handler
    events:
      - http:
          path: hello
          method: get

custom:
  esbuild:
    watch:
      pattern: ["src/**/*.ts"] # match only typescript files in src directory
      ignore: ["temp/**/*"]
